version: '3'

services:
  package-server:
    build: .
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      package-db:
        condition: service_healthy
    networks:
      - package

  package-db:
    image: postgres:16-alpine
    networks:
      package:
        aliases:
          - 'db'
    environment:
      - POSTGRES_USER=package
      - POSTGRES_PASSWORD=package
      - POSTGRES_DB=package
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U package']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  package:
    driver: bridge
