-- AlterTable
ALTER TABLE "InventoryItem" ALTER COLUMN "count" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Trade" ALTER COLUMN "count" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Truck" ALTER COLUMN "resourceCount" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "TruckSchedule" ALTER COLUMN "resourceCount" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "money" SET DATA TYPE BIGINT,
ALTER COLUMN "gems" SET DATA TYPE BIGINT,
ALTER COLUMN "experience" SET DATA TYPE BIGINT;
